import {
  createOptimizerArtifactSet,
  hasOptimizerErrors
} from "./build-optimizer.js";

export const BUILD_PROFILE_VERSION = 1;
export const BUILD_PROFILE_NAME = "build-required";
export const VIRTUAL_PLAN_ID = "virtual:async-framework/generated-plan";
export const RESOLVED_VIRTUAL_PLAN_ID = "\0virtual:async-framework/generated-plan";

export function createBuildProfileReport(fixture = {}, options = {}) {
  const artifactSet = createOptimizerArtifactSet(fixture);
  const diagnostics = [...artifactSet.diagnostics];
  const plan = createBuildProfilePlan(fixture, artifactSet);
  const bootstrap = createBuildProfileBootstrap(artifactSet.report.runtime.entrypoint);
  const report = {
    version: BUILD_PROFILE_VERSION,
    profile: BUILD_PROFILE_NAME,
    mode: options.mode ?? fixture.mode ?? "development",
    host: normalizeBuildHost(fixture.sourceInventory?.config?.host),
    runtime: artifactSet.report.runtime,
    signals: artifactSet.report.signals,
    events: artifactSet.report.events,
    handlers: artifactSet.report.handlers,
    stream: artifactSet.report.stream,
    serverOnlyModuleExclusions: artifactSet.report.serverOnlyModuleExclusions,
    generatedLocatorCount: artifactSet.report.generatedLocatorCount,
    virtualModules: [VIRTUAL_PLAN_ID],
    diagnostics
  };

  return {
    version: BUILD_PROFILE_VERSION,
    profile: BUILD_PROFILE_NAME,
    artifacts: artifactSet.artifacts,
    diagnostics,
    failed: hasOptimizerErrors(diagnostics),
    plan,
    report,
    bootstrap
  };
}

export function createBuildProfilePlan(fixture = {}, artifactSet = createOptimizerArtifactSet(fixture)) {
  if (fixture.runtimePlan) {
    return normalizeRuntimePlan(fixture.runtimePlan);
  }

  const locators = artifactSet.artifacts.jsxSemanticGraph.locators;
  const signalSources = artifactSet.artifacts.signalSources.sources;
  const eventSymbols = artifactSet.artifacts.eventSymbols.events;
  const elementIndex = new Map(locators.map((locator, index) => [locator, index]));
  const plan = {
    version: 1,
    elements: locators,
    signals: undefined,
    events: undefined
  };

  const values = signalSources
    .filter((source) => source.kind === "writable")
    .map((source) => [source.sourceId, source.initialValue]);
  if (values.length > 0) {
    plan.signals = {
      version: 1,
      values,
      bindings: fixture.signalBindings ?? []
    };
  }

  if (eventSymbols.length > 0) {
    plan.events = {
      version: 1,
      events: eventSymbols.map((event) => [
        elementIndex.get(event.elementId) ?? 0,
        event.eventType,
        event.commands
      ]),
      handlers: fixture.handlers ?? {}
    };
  }

  return withoutUndefined(plan);
}

export function createBuildProfileBootstrap(entrypoint) {
  return {
    entrypoint,
    virtualPlan: VIRTUAL_PLAN_ID,
    usesAsyncGlobal: false,
    importsRootAsync: false
  };
}

export function emitGeneratedPlanModule(profile) {
  return [
    "// Generated by @async/framework/vite. Do not edit.",
    `export const plan = ${stableJson(profile.plan)};`,
    `export const report = ${stableJson(profile.report)};`,
    "export default plan;",
    ""
  ].join("\n");
}

export function emitBootstrapModule(profile) {
  return [
    "// Generated by @async/framework/vite. Do not edit.",
    `import { start } from ${JSON.stringify(profile.bootstrap.entrypoint)};`,
    `import { plan, report } from ${JSON.stringify(VIRTUAL_PLAN_ID)};`,
    "",
    "export { plan, report };",
    "export function startAsyncFramework(root = document, options = {}) {",
    "  return start(root, plan, options);",
    "}",
    ""
  ].join("\n");
}

function normalizeRuntimePlan(plan) {
  if (!plan || typeof plan !== "object") {
    throw new TypeError("Build profile runtime plan must be an object.");
  }
  if (plan.version !== 1) {
    throw new Error(`Unsupported build profile runtime plan version: ${String(plan.version)}.`);
  }
  return {
    version: 1,
    ...plan
  };
}

function normalizeBuildHost(host = {}) {
  return {
    name: host.name ?? "vite",
    version: host.version ?? String(host.major ?? host.versionMajor ?? "8"),
    engine: host.engine ?? "rolldown"
  };
}

function withoutUndefined(value) {
  return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined));
}

function stableJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}
